packages:
  - "."
  - "*"
overrides:
  shell-quote: ">=1.8.4"
  esbuild: ">=0.28.1"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
